### ISSUE TITLE
a task that i want to solve

### ISSUE THREAD

**Issue by ghost** [sawitrerkyindee/GCNs_pytorch#1]
@sawitrerkyindee 
hi there,
i would like to discuss with you a task that i would like to solve,
are you interested in freelancing?
what is your email so that i discus with further details?

waiting for your reply

**Comment by sawitrerkyindee** [comment]
Hi

Thank you for your email.
I am interested. I would like to know more detail about this project.

You can reach me via srerkyindee@gmail.com

Best Regards,
Sawit

**Comment by ghost** [comment]
To be continued by email...
